-- 7-1
SELECT DEPTNO,
       TRUNC(AVG(SAL)) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY DEPTNO; 

--FIRST_VERSION
SELECT DEPTNO, 
       ROUND(AVG(SAL)) AS AVG_SAL, --소수점을 제외해야함으로 ROUND 보다 TRUNC를 사용해야함
       MAX(SAL) AS MAX_SAL, 
       MIN(SAL) AS MIN_SAL, 
       COUNT(DEPTNO) AS CNT
    FROM EMP
GROUP BY DEPTNO;

-- 7-2
SELECT JOB,
       COUNT(*)
  FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3; --HAVING절 사용해야함

-- 7-3
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;
--연도를 뽑고 뽑은 연도와 부서별로 GROUP BY 해야함

-- 7-4
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY NVL2(COMM, 'O', 'X'); 

-- 7-5
SELECT DEPTNO,
       TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       COUNT(*) AS CNT,
       MAX(SAL) AS MAX_SAL,
       SUM(SAL) AS SUM_SAL,
       AVG(SAL) AS AVG_SAL
  FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY')); 
--ROULLUP 함수 사용해서 뿌림
