-- 13-1
--① 
CREATE TABLE EMPIDX
 AS SELECT * 
      FROM EMP;
SELECT * FROM EMPIDX;
--② 
CREATE INDEX IDX_EMPIDX_EMPNO 
    ON EMPIDX (EMPNO);
SELECT * FROM USER_IND_COLUMNS;
	     
--③
SELECT * 
  FROM USER_INDEXES 
 WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

--수업.ver
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';
SELECT * FROM USER_IND_COLUMNS;

-- 13-2
CREATE OR REPLACE VIEW EMPIDX_OVER15K 
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, 
               SAL, NVL2(COMM, 'O', 'X') AS COMM 
          FROM EMPIDX 
         WHERE SAL > 1500); 

--수업.ver
SELECT * FROM USER_VIEWS;
CREATE VIEW EMPIDX_OVER15K
 AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM,'O','X') AS COMM
   FROM EMPIDX
  WHERE SAL > 1500);
SELECT * FROM USER_VIEWS;
CREATE OR REPLACE VIEW EMPIDX_OVER15K
 AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM,'O','X') AS COMM
   FROM EMPIDX
  WHERE SAL > 1500);
SELECT * FROM USER_VIEWS;

-- 13-3
--①
CREATE TABLE DEPTSEQ
    AS SELECT * 
         FROM DEPT; 
SELECT * FROM DEPTSEQ;
--② 
CREATE SEQUENCE SEQ_DEPTSEQ 
   INCREMENT BY 1
   START WITH 1
   MAXVALUE 99
   MINVALUE 1
   NOCYCLE 
   NOCACHE;
SELECT * FROM USER_SEQUENCES;
   
--③
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC) 
VALUES (SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');

--수업.ver
INSERT INTO DEPTSEQ
 VALUES(SEQ_DEPTSEQ_SEQUENCE.NEXTVAL,'DATABASE','SEOUL');
INSERT INTO DEPTSEQ
 VALUES(SEQ_DEPTSEQ_SEQUENCE.NEXTVAL,'WEB','BUSAN');
INSERT INTO DEPTSEQ
 VALUES(SEQ_DEPTSEQ_SEQUENCE.NEXTVAL,'MOBILE','ILSAN');
SELECT * FROM DEPTSEQ;
--
