--P102
SELECT *
    FROM EMP
  WHERE SAL >= 2500
   AND JOB = 'ANALYST';

--P135
SELECT SUBSTR(ENAME, 3)
    FROM EMP;


--P194
SELECT DEPTNO, JOB, AVG(SAL)
    FROM EMP
  GROUP BY DEPTNO, JOB
    HAVING AVG(SAL) >= 500
  ORDER BY DEPTNO, JOB;