--문제3 UPDATE, SUBQUERRY
--서브쿼리
SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50;
--확인
SELECT * FROM CHAP10HW_EMP WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50);
--변경
UPDATE CHAP10HW_EMP
   SET DEPTNO = 70
  WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50);
SELECT * FROM CHAP10HW_EMP;


--문제4 UPDATE, SUBQUERRY
--서브쿼리
SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60;
--확인
SELECT * FROM CHAP10HW_EMP WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60);
--변경
UPDATE CHAP10HW_EMP
   SET SAL = SAL*1.1,
       DEPTNO = 80
   WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60);
SELECT * FROM CHAP10HW_EMP;



--문제5 DELETE, SUBQUERRY
--서브쿼리
SELECT E.EMPNO FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
      AND S.GRADE = 5;
--확인
SELECT * FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
      AND S.GRADE = 5;
--삭제
DELETE FROM CHAP10HW_EMP
  WHERE EMPNO IN (SELECT E.EMPNO FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
      AND S.GRADE = 5);
SELECT * FROM CHAP10HW_EMP;
--